import type { PageCopyEntry } from "@/content/page-copy/types";

export const adminPageCopy: PageCopyEntry[] = [
  {
    route: "/admin/panel",
    title: "Dashboard Humas Admin",
    description: "Ringkasan sistem dan pintu masuk ke seluruh area administrasi.",
    heroEyebrow: "Area Admin",
    heroTitle: "Dashboard humas admin",
    heroDescription: "Kelola layanan, penugasan, operasional, dan kontrol lintas sistem dari satu workspace pusat.",
    primaryAction: { label: "Buka Katalog Layanan", href: "/admin/panel/layanan", variant: "primary" },
    secondaryAction: { label: "Aktivitas Sistem", href: "/admin/panel/aktivitas", variant: "secondary" },
  },
  {
    route: "/admin/panel/layanan",
    title: "Katalog Layanan",
    description: "Kelola layanan publik, status aktif, dan struktur katalog.",
    heroEyebrow: "Administrasi Layanan",
    heroTitle: "Katalog layanan",
    heroDescription: "Tambahkan, ubah, dan rapikan layanan publik agar jalur booking dan antrean tetap akurat.",
    primaryAction: { label: "Tambah Layanan", variant: "primary" },
    secondaryAction: { label: "Dashboard", href: "/admin/panel", variant: "secondary" },
  },
  {
    route: "/admin/panel/login-penugasan",
    title: "Akun dan Penugasan",
    description: "Kelola akun resmi, peran, unit, dan cakupan layanan.",
    heroEyebrow: "Manajemen Akun",
    heroTitle: "Login dan penugasan",
    heroDescription: "Atur petugas operasional, peran kerja, dan penugasan unit atau layanan dari satu halaman.",
    primaryAction: { label: "Tambah Akun", variant: "primary" },
    secondaryAction: { label: "Hak Akses Role", href: "/admin/panel/hak-akses-role", variant: "secondary" },
  },
  {
    route: "/admin/panel/unit-organisasi",
    title: "Unit Organisasi",
    description: "Atur layanan, kuota, dan konfigurasi tiap unit organisasi.",
    heroEyebrow: "Konfigurasi Unit",
    heroTitle: "Unit organisasi",
    heroDescription: "Kelola layanan aktif per unit, kuota harian, dan aturan operasional yang melekat ke unit.",
    primaryAction: { label: "Simpan Konfigurasi", variant: "primary" },
    secondaryAction: { label: "Operasional", href: "/admin/panel/operasional", variant: "secondary" },
  },
  {
    route: "/admin/panel/pengumuman",
    title: "Pengumuman",
    description: "Kelola informasi publik dan banner yang tampil di portal.",
    heroEyebrow: "Komunikasi Publik",
    heroTitle: "Pengumuman layanan",
    heroDescription: "Buat, ubah, dan atur masa tayang pengumuman agar informasi publik tetap relevan.",
    primaryAction: { label: "Tambah Pengumuman", variant: "primary" },
    secondaryAction: { label: "FAQ & Bantuan", href: "/admin/panel/faq-bantuan", variant: "secondary" },
  },
  {
    route: "/admin/panel/operasional",
    title: "Operasional",
    description: "Atur jam layanan, hari kerja, dan parameter operasi sistem.",
    heroEyebrow: "Operasional Sistem",
    heroTitle: "Jam dan aturan operasional",
    heroDescription: "Pastikan jam layanan, hari libur, dan parameter booking mengikuti kebijakan LKPP yang berlaku.",
    primaryAction: { label: "Simpan Operasional", variant: "primary" },
    secondaryAction: { label: "Unit Organisasi", href: "/admin/panel/unit-organisasi", variant: "secondary" },
  },
  {
    route: "/admin/panel/faq-bantuan",
    title: "FAQ dan Bantuan",
    description: "Kelola bantuan publik dan FAQ yang dibaca pengguna.",
    heroEyebrow: "Pusat Bantuan",
    heroTitle: "FAQ dan bantuan publik",
    heroDescription: "Pastikan FAQ yang tampil untuk pengguna selalu selaras dengan layanan dan kebijakan terbaru.",
    primaryAction: { label: "Tambah FAQ", variant: "primary" },
    secondaryAction: { label: "Pengumuman", href: "/admin/panel/pengumuman", variant: "secondary" },
  },
  {
    route: "/admin/panel/hak-akses-role",
    title: "Hak Akses Role",
    description: "Kelola permission dan cakupan kerja untuk tiap role operasional.",
    heroEyebrow: "Governance",
    heroTitle: "Hak akses role",
    heroDescription: "Atur apa yang bisa dilakukan tiap role agar operasional tetap aman, jelas, dan mudah diaudit.",
    primaryAction: { label: "Simpan Hak Akses", variant: "primary" },
    secondaryAction: { label: "Akun & Penugasan", href: "/admin/panel/login-penugasan", variant: "secondary" },
  },
  {
    route: "/admin/panel/ekspor-data",
    title: "Ekspor Data",
    description: "Unduh data layanan dan antrean untuk laporan atau kebutuhan audit.",
    heroEyebrow: "Pusat Ekspor",
    heroTitle: "Ekspor data sistem",
    heroDescription: "Siapkan file laporan dari data antrean, layanan, atau monitoring lintas unit.",
    primaryAction: { label: "Ekspor CSV", variant: "primary" },
    secondaryAction: { label: "Aktivitas Sistem", href: "/admin/panel/aktivitas", variant: "secondary" },
  },
  {
    route: "/admin/panel/data-referensi",
    title: "Data Referensi",
    description: "Kelola master data dan kapasitas dasar sistem layanan.",
    heroEyebrow: "Master Data",
    heroTitle: "Data referensi sistem",
    heroDescription: "Baca dan rapikan data referensi yang dipakai oleh layanan, unit, dan operasional.",
    primaryAction: { label: "Simpan Referensi", variant: "primary" },
    secondaryAction: { label: "Katalog Layanan", href: "/admin/panel/layanan", variant: "secondary" },
  },
  {
    route: "/admin/panel/aktivitas",
    title: "Aktivitas Sistem",
    description: "Audit trail dan jejak perubahan lintas sistem.",
    heroEyebrow: "Audit Sistem",
    heroTitle: "Aktivitas sistem",
    heroDescription: "Pantau jejak perubahan, tindakan admin, dan event yang penting untuk audit operasional.",
    primaryAction: { label: "Muat Ulang Log", variant: "primary" },
    secondaryAction: { label: "Ekspor Data", href: "/admin/panel/ekspor-data", variant: "secondary" },
  },
];
