import type { PageCopyEntry } from "@/content/page-copy/types";

export const monitoringPageCopy: PageCopyEntry[] = [
  {
    route: "/supervisor/dashboard",
    title: "Dashboard Supervisor Monitoring",
    description: "Ringkasan layanan lintas unit atau unit penugasan.",
    heroEyebrow: "Area Monitoring",
    heroTitle: "Ringkasan layanan",
    heroDescription: "Pantau antrean, kehadiran, dan hal-hal yang perlu perhatian dari satu dashboard monitoring.",
    primaryAction: { label: "Buka Monitoring", href: "/supervisor/monitoring", variant: "primary" },
    secondaryAction: { label: "Ekspor Data", href: "/supervisor/data-ekspor", variant: "secondary" },
  },
  {
    route: "/supervisor/monitoring",
    title: "Monitoring Layanan",
    description: "Grafik, filter, dan daftar prioritas untuk pengawasan layanan.",
    heroEyebrow: "Monitoring Detail",
    heroTitle: "Pantau layanan dan antrean",
    heroDescription: "Atur periode, unit, dan layanan untuk membaca performa dan anomali operasional secara lebih detail.",
    primaryAction: { label: "Muat Ulang", variant: "primary" },
    secondaryAction: { label: "Ekspor Data", href: "/supervisor/data-ekspor", variant: "secondary" },
  },
  {
    route: "/supervisor/data-ekspor",
    title: "Ekspor Data Monitoring",
    description: "Unduh data pengawasan dalam format operasional yang dibutuhkan.",
    heroEyebrow: "Pusat Ekspor",
    heroTitle: "Ekspor data monitoring",
    heroDescription: "Gunakan filter aktif untuk menyiapkan file CSV, JSON, atau SQL dari data layanan dan antrean.",
    primaryAction: { label: "Ekspor CSV", variant: "primary" },
    secondaryAction: { label: "Kembali ke Monitoring", href: "/supervisor/monitoring", variant: "secondary" },
  },
  {
    route: "/humas-monitoring/dashboard",
    title: "Dashboard Humas Monitoring",
    description: "Ringkasan layanan dan informasi publik lintas unit.",
    heroEyebrow: "Humas Monitoring",
    heroTitle: "Ringkasan layanan publik",
    heroDescription: "Pantau antrean, notifikasi layanan, dan hal-hal yang menyentuh pengalaman warga.",
    primaryAction: { label: "Buka Monitoring", href: "/humas-monitoring/monitoring", variant: "primary" },
    secondaryAction: { label: "Ekspor Data", href: "/humas-monitoring/data-ekspor", variant: "secondary" },
  },
  {
    route: "/humas-monitoring/monitoring",
    title: "Monitoring Humas",
    description: "Pantau layanan, antrean, dan komunikasi publik berdasarkan data operasional.",
    heroEyebrow: "Monitoring Publik",
    heroTitle: "Pantau layanan lintas unit",
    heroDescription: "Baca ritme layanan dan lihat area yang perlu perhatian komunikasi atau tindak lanjut publik.",
    primaryAction: { label: "Muat Ulang", variant: "primary" },
    secondaryAction: { label: "Ekspor Data", href: "/humas-monitoring/data-ekspor", variant: "secondary" },
  },
  {
    route: "/humas-monitoring/data-ekspor",
    title: "Ekspor Data Humas Monitoring",
    description: "Unduh data monitoring untuk kebutuhan laporan dan koordinasi.",
    heroEyebrow: "Pusat Ekspor",
    heroTitle: "Ekspor data humas monitoring",
    heroDescription: "Siapkan file lintas unit dari filter monitoring yang sedang aktif.",
    primaryAction: { label: "Ekspor CSV", variant: "primary" },
    secondaryAction: { label: "Dashboard", href: "/humas-monitoring/dashboard", variant: "secondary" },
  },
];
