import type { PageCopyEntry } from "@/content/page-copy/types";

export const unitPageCopy: PageCopyEntry[] = [
  {
    route: "/unit/dashboard",
    title: "Dashboard Unit Organisasi",
    description: "Ringkasan antrean unit dan kontrol layanan harian.",
    heroEyebrow: "Area Unit",
    heroTitle: "Fokus kerja unit",
    heroDescription: "Pantau antrean berikutnya, ritme layanan aktif, dan ringkasan harian unit organisasi.",
    primaryAction: { label: "Buka Data Antrean", href: "/unit/data-antrean", variant: "primary" },
    secondaryAction: { label: "Analitik Unit", href: "/unit/analitik-unit", variant: "secondary" },
  },
  {
    route: "/unit/data-antrean",
    title: "Data Antrean Unit",
    description: "Workspace operasional untuk memanggil, memulai, menyelesaikan, dan memindahkan antrean.",
    heroEyebrow: "Workspace Operasional",
    heroTitle: "Data antrean unit",
    heroDescription: "Kelola antrean yang masuk ke unit, tambahkan catatan, prioritas, dan tindak lanjuti layanan sampai selesai.",
    primaryAction: { label: "Muat Ulang", variant: "primary" },
    secondaryAction: { label: "Analitik Unit", href: "/unit/analitik-unit", variant: "secondary" },
  },
  {
    route: "/unit/analitik-unit",
    title: "Analitik Unit",
    description: "Insight performa unit, volume layanan, dan ritme penyelesaian.",
    heroEyebrow: "Analitik Internal",
    heroTitle: "Analitik layanan unit",
    heroDescription: "Gunakan data harian unit untuk membaca volume antrean, penyelesaian, dan titik layanan yang perlu perhatian.",
    primaryAction: { label: "Buka Data Antrean", href: "/unit/data-antrean", variant: "primary" },
    secondaryAction: { label: "Dashboard", href: "/unit/dashboard", variant: "secondary" },
  },
  {
    route: "/unit/profil",
    title: "Profil Unit Organisasi",
    description: "Identitas akun unit, cakupan layanan, dan ringkasan penugasan.",
    heroEyebrow: "Profil Petugas Unit",
    heroTitle: "Profil unit organisasi",
    heroDescription: "Lihat identitas akun, layanan yang ditangani, dan cakupan unit yang sedang aktif.",
    primaryAction: { label: "Perbarui Profil", variant: "primary" },
    secondaryAction: { label: "Pengaturan", href: "/unit/pengaturan", variant: "secondary" },
  },
  {
    route: "/unit/pengaturan",
    title: "Pengaturan Unit Organisasi",
    description: "Preferensi kerja, tampilan data antrean, dan opsi notifikasi unit.",
    heroEyebrow: "Preferensi Unit",
    heroTitle: "Pengaturan unit organisasi",
    heroDescription: "Atur preferensi dasar agar workspace unit tetap nyaman dipakai dan mudah diaudit.",
    primaryAction: { label: "Simpan Pengaturan", variant: "primary" },
    secondaryAction: { label: "Dashboard", href: "/unit/dashboard", variant: "secondary" },
  },
];
