import type { PageCopyEntry } from "@/content/page-copy/types";

export const userPageCopy: PageCopyEntry[] = [
  {
    route: "/dashboard",
    title: "Dashboard Pengguna",
    description: "Pantau antrian aktif dan riwayat layanan.",
    heroEyebrow: "Dashboard",
    heroTitle: "Informasi Antrian",
    heroDescription: "Lihat antrian aktif dan jadwal terdekat.",
    primaryAction: { label: "Ambil antrian", href: "/layanan", variant: "primary" },
    secondaryAction: { label: "Jadwal Saya", href: "/jadwal-saya", variant: "secondary" },
  },
  {
    route: "/layanan",
    title: "Ambil Antrian",
    description: "Pilih layanan yang sesuai lalu lanjutkan antrian.",
    heroEyebrow: "",
    heroTitle: "Pilih layanan",
    heroDescription: "",
    primaryAction: { label: "Mulai", variant: "primary" },
    secondaryAction: { label: "Jadwal Saya", href: "/jadwal-saya", variant: "secondary" },
  },
  {
    route: "/jadwal-saya",
    title: "Jadwal Saya",
    description: "Lihat antrian aktif dan riwayat layanan.",
    heroEyebrow: "Jadwal",
    heroTitle: "Jadwal Saya",
    heroDescription: "Pantau antrian yang sedang berjalan dan riwayat layanan.",
    primaryAction: { label: "Ambil antrian", href: "/layanan", variant: "primary" },
    secondaryAction: { label: "Buka Bantuan", href: "/bantuan", variant: "secondary" },
  },
  {
    route: "/bantuan",
    title: "Bantuan Pengguna",
    description: "Jawaban cepat untuk antrian dan akun.",
    heroEyebrow: "Pusat Bantuan",
    heroTitle: "Bantuan",
    heroDescription: "Temukan jawaban cepat seputar antrian dan akun.",
    primaryAction: { label: "Buka FAQ", variant: "primary" },
    secondaryAction: { label: "Kembali ke Layanan", href: "/layanan", variant: "secondary" },
  },
  {
    route: "/profil",
    title: "Profil Pengguna",
    description: "Kelola data akun dan data wajib booking.",
    heroEyebrow: "Profil",
    heroTitle: "Profil akun",
    heroDescription: "Lengkapi data agar antrian tetap lancar.",
    primaryAction: { label: "Simpan Profil", variant: "primary" },
    secondaryAction: { label: "Pengaturan", href: "/pengaturan", variant: "secondary" },
  },
  {
    route: "/pengaturan",
    title: "Pengaturan Pengguna",
    description: "Atur preferensi akun.",
    heroEyebrow: "Pengaturan",
    heroTitle: "Pengaturan akun",
    heroDescription: "Sesuaikan preferensi dasar akun.",
    primaryAction: { label: "Simpan Pengaturan", variant: "primary" },
    secondaryAction: { label: "Kembali ke Dashboard", href: "/dashboard", variant: "secondary" },
  },
];
