import type { LegacyRouteAlias } from "@/content/legacy-flow/types";

export const legacyRouteAliasMap: LegacyRouteAlias[] = [
  { legacyPath: "/", nextPath: "/", status: "done" },
  { legacyPath: "/home", nextPath: "/dashboard", status: "partial", note: "Konten parity user dashboard masih bertahap." },
  { legacyPath: "/book", nextPath: "/layanan", status: "partial", note: "Wizard penuh akan dipisah ke route dedicated." },
  { legacyPath: "/book/:serviceId", nextPath: "/layanan/[serviceId]", status: "partial" },
  { legacyPath: "/appointments", nextPath: "/jadwal-saya", status: "partial" },
  { legacyPath: "/appointments/:id", nextPath: "/jadwal-saya/[appointmentId]", status: "partial" },
  { legacyPath: "/help", nextPath: "/bantuan", status: "partial" },
  { legacyPath: "/profile", nextPath: "/profil", status: "partial" },
  { legacyPath: "/petugas", nextPath: "/login/petugas", status: "partial" },
  { legacyPath: "/petugas/profile", nextPath: "/login/petugas", status: "todo", note: "Forced reset PIN flow baru belum parity dengan profile shared legacy." },
  { legacyPath: "/admin", nextPath: "/admin", status: "done", note: "Admin legacy sekarang langsung diarahkan ke login petugas humas admin." },
  { legacyPath: "/admin/panel/profile", nextPath: "/admin/panel/profile", status: "done" },
  { legacyPath: "/resepsionis/dashboard", nextPath: "/resepsionis/dashboard", status: "done" },
  { legacyPath: "/resepsionis/dashboard/riwayat", nextPath: "/resepsionis/riwayat", status: "partial" },
  { legacyPath: "/resepsionis/dashboard/profil", nextPath: "/resepsionis/profil", status: "done" },
  { legacyPath: "/resepsionis/dashboard/pengaturan", nextPath: "/resepsionis/pengaturan", status: "done" },
  { legacyPath: "/unor/dashboard", nextPath: "/unit/dashboard", status: "done" },
  { legacyPath: "/unor/dashboard/data-antrean", nextPath: "/unit/data-antrean", status: "partial" },
  { legacyPath: "/unor/dashboard/analitik-unit", nextPath: "/unit/analitik-unit", status: "partial" },
  { legacyPath: "/unor/dashboard/laporan-ekspor", nextPath: "/unit/analitik-unit", status: "partial", note: "Alias laporan-ekspor mengikuti workspace analitik unit." },
  { legacyPath: "/supervisor/dashboard", nextPath: "/supervisor/dashboard", status: "done" },
  { legacyPath: "/supervisor/dashboard/monitoring", nextPath: "/supervisor/monitoring", status: "partial" },
  { legacyPath: "/supervisor/dashboard/data-ekspor", nextPath: "/supervisor/data-ekspor", status: "partial" },
  { legacyPath: "/supervisor/dashboard/profil", nextPath: "/supervisor/profil", status: "partial" },
  { legacyPath: "/lobby", nextPath: "/lobby", status: "done", note: "Check-in lobby sudah fokus ke frontdesk hari ini." },
  {
    legacyPath: "/offline-visitor",
    nextPath: "/offline-visitor",
    status: "partial",
    note: "Walk-in frontdesk sudah punya route kanonis, parity bisnis masih bertahap.",
  },
  {
    legacyPath: "/resepsionis/offline-visitor",
    nextPath: "/offline-visitor",
    status: "done",
    note: "Alias resepsionis sekarang redirect ke route kanonis walk-in.",
  },
  { legacyPath: "/admin/panel", nextPath: "/admin/panel", status: "done" },
  { legacyPath: "/admin/panel/services", nextPath: "/admin/panel/layanan", status: "partial" },
  { legacyPath: "/admin/panel/staff", nextPath: "/admin/panel/login-penugasan", status: "partial" },
  { legacyPath: "/admin/panel/hours", nextPath: "/admin/panel/operasional", status: "partial" },
  { legacyPath: "/admin/panel/unor", nextPath: "/admin/panel/unit-organisasi", status: "partial" },
  { legacyPath: "/admin/panel/announcements", nextPath: "/admin/panel/pengumuman", status: "partial" },
  { legacyPath: "/admin/panel/helpfaq", nextPath: "/admin/panel/faq-bantuan", status: "partial" },
  { legacyPath: "/admin/panel/roles", nextPath: "/admin/panel/hak-akses-role", status: "partial" },
  { legacyPath: "/admin/panel/export", nextPath: "/admin/panel/ekspor-data", status: "partial" },
  { legacyPath: "/admin/panel/masterdata", nextPath: "/admin/panel/data-referensi", status: "partial" },
  { legacyPath: "/admin/panel/audit", nextPath: "/admin/panel/aktivitas", status: "partial" },
];
